import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "../providers/SessionProvider";
import Sidebar from "@/src/containers/Sidebar";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import QueryProvider from "../utils/QueryProvider";
config.autoAddCss = false

export const metadata: Metadata = {
  title: "Reminder",
  description: "Generated by Yooni",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex overflow-hidden">
        <QueryProvider>
          <SessionProvider>
            {children}
            <div id='modal-portal' />
          </SessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
