import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false

export const metadata: Metadata = {
  title: "Reminder",
  description: "Generated by Yooni",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex overflow-hidden">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
